/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "friend_request" CASCADE;

CREATE TABLE "friend_request" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "user_id" varchar(64) NOT NULL,
  "peer_id" varchar(64) NOT NULL);

CREATE INDEX "friend_request_user_id_i"
  ON "friend_request" ("user_id");

CREATE INDEX "friend_request_peer_id_i"
  ON "friend_request" ("peer_id");

