/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE DATABASE IF NOT EXISTS `huzch`;
USE `huzch`;
DROP TABLE IF EXISTS `friend_request`;

CREATE TABLE `friend_request` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` varchar(64) NOT NULL,
  `peer_id` varchar(64) NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `user_id_i`
  ON `friend_request` (`user_id`);

CREATE INDEX `peer_id_i`
  ON `friend_request` (`peer_id`);

