/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "relation" CASCADE;

CREATE TABLE "relation" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "user_id" varchar(64) NOT NULL,
  "peer_id" varchar(64) NOT NULL);

CREATE INDEX "relation_user_id_i"
  ON "relation" ("user_id");

