/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE DATABASE IF NOT EXISTS `huzch`;
USE `huzch`;
DROP TABLE IF EXISTS `session_member`;

CREATE TABLE `session_member` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `session_id` varchar(64) NOT NULL,
  `user_id` varchar(64) NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `session_id_i`
  ON `session_member` (`session_id`);

