/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "session_member" CASCADE;

CREATE TABLE "session_member" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "session_id" varchar(64) NOT NULL,
  "user_id" varchar(64) NOT NULL);

CREATE INDEX "session_member_session_id_i"
  ON "session_member" ("session_id");

