/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE DATABASE IF NOT EXISTS `huzch`;
USE `huzch`;
DROP TABLE IF EXISTS `session`;

CREATE TABLE `session` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `session_id` varchar(64) NOT NULL,
  `session_name` varchar(64) NOT NULL,
  `session_type` ENUM('SINGLE', 'GROUP') NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `session_id_i`
  ON `session` (`session_id`);

