/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "session" CASCADE;

CREATE TABLE "session" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "session_id" varchar(64) NOT NULL,
  "session_name" varchar(64) NOT NULL,
  "session_type" INTEGER NOT NULL);

CREATE UNIQUE INDEX "session_session_id_i"
  ON "session" ("session_id");

