/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE DATABASE IF NOT EXISTS `huzch`;
USE `huzch`;
DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` varchar(64) NOT NULL,
  `avatar_id` varchar(64) NULL,
  `name` varchar(64) NULL,
  `phone` varchar(64) NULL,
  `password` varchar(64) NULL,
  `description` TEXT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `user_id_i`
  ON `user` (`user_id`);

CREATE UNIQUE INDEX `name_i`
  ON `user` (`name`);

CREATE UNIQUE INDEX `phone_i`
  ON `user` (`phone`);

