/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE "user" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "user_id" varchar(64) NOT NULL,
  "avatar_id" varchar(64) NULL,
  "name" varchar(64) NULL,
  "phone" varchar(64) NULL,
  "password" varchar(64) NULL,
  "description" TEXT NULL);

CREATE UNIQUE INDEX "user_user_id_i"
  ON "user" ("user_id");

CREATE UNIQUE INDEX "user_name_i"
  ON "user" ("name");

CREATE UNIQUE INDEX "user_phone_i"
  ON "user" ("phone");

